services:
  mongodb:
    image: mongo:6
    container_name: wafa_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - wafa-network

  backend:
    build:
      context: ./wafa-backend
      dockerfile: Dockerfile
    container_name: wafa_backend
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - PORT=5010
      - MONGO_URL=mongodb://mongodb:27017/wafa
    networks:
      - wafa-network

  frontend:
    build:
      context: ./wafa-frentend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_BASED_URL=${VITE_BASED_URL}
    container_name: wafa_frontend
    restart: always
    networks:
      - wafa-network

  nginx-gateway:
    image: nginx:alpine
    container_name: wafa_nginx_gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-gateway/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - wafa-network

  certbot:
    image: certbot/certbot
    container_name: wafa_certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - wafa-network

networks:
  wafa-network:
    driver: bridge

volumes:
  mongodb_data:
